// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buwhfvjcgwfegzmcxdcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1d2hmdmpjZ3dmZWd6bWN4ZGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDYxNTUsImV4cCI6MjA2ODIyMjE1NX0.fZhahDJg2MKtjKoI8dgECj8qdCrPm13RMx8rv-1v_N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});